[package]
name = "client"
version = "0.1.0"
authors = ["glepur <goran.lepur1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.20"
instant = { version = "0.1.2", features = [ "stdweb" ] }
